// frontend/react/src/components/ToDoList/ToDoItem/ToDoItem.tsx
import React, { ChangeEvent, useEffect, useRef, useState } from 'react';
import { ItemList, ItemListLevel } from '../../../types/common';
import { classNameLevel, INPUT_NAME, MAX_LEVEL, MIN_LEVEL } from './constants';
import { ARROW_DOWN, ENTER, ARROW_UP, TAB, BACKSPACE } from './../../../contants/contants';
import styles from './todoItem.module.css';
import commonStyles from '../../../commonStyles.module.css';

const ToDoItem = (props: {
  currentIndexFocus: number;
  index: number;
  item: ItemList;
  onUpdateItem: (item: ItemList) => void;
  onRemoveItem: (id: string) => void;
  onAddItem: ({
    value,
    index,
    level,
    id
  }: {
    value: string;
    index?: number;
    level?: ItemListLevel;
    id?: string;
  }) => void;
  isLastItem?: boolean;
}) => {
  const {
    item: { text, id, isDone, level },
    item,
    index,
    onUpdateItem,
    onRemoveItem,
    onAddItem,
    isLastItem,
    currentIndexFocus
  } = props;

  const inputRef = useRef<HTMLInputElement>(null);

  const [newValue, setNewValue] = useState(text);
  const [isChecked, setIsChecked] = useState(isDone);

  useEffect(() => {
    if (currentIndexFocus === index) {
      inputRef?.current?.focus();
    }
  }, []);

  const updateHandler = () => {
    if (!isLastItem || (isLastItem && newValue.trim() !== '')) {
      onUpdateItem({ ...item, text: newValue, isDone: isChecked });
    }

    if (isLastItem) {
      setNewValue('');
      setIsChecked(false);
    }
  };

  const editItemStatusHandler = () => {
    setIsChecked((isChecked) => !isChecked);
    if (!isLastItem) {
      onUpdateItem({ ...item, isDone: !isChecked });
    }
  };

  const updateValueHandler = (e: ChangeEvent<HTMLInputElement>) => {
    setNewValue(e.currentTarget.value);
  };

  const keyDownHandler = async (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.code === ENTER) {
      if (e.metaKey) {
        editItemStatusHandler();
      } else if (e.currentTarget?.value !== '') {
        if (isLastItem) {
          onAddItem({ value: e.currentTarget.value });
          setNewValue('');
        } else {
          updateHandler();
          onAddItem({ value: '', index, level, id });
        }
      }
    } else if (e.code === BACKSPACE && e.currentTarget?.value === '') {
      const newName = INPUT_NAME + (Number(e.currentTarget.name.replace(/\D/g, '')) - 1);
      const prevSibling = document.querySelector(`input[name=${newName}]`) as HTMLInputElement;
      prevSibling?.focus();

      onRemoveItem(id);
      e.preventDefault();
    } else if (e.code === ARROW_DOWN) {
      const newName = INPUT_NAME + (Number(e.currentTarget.name.replace(/\D/g, '')) + 1);
      const nextSibling = document.querySelector(`input[name=${newName}]`) as HTMLInputElement;
      nextSibling?.focus();
    } else if (e.code === ARROW_UP) {
      const newName = INPUT_NAME + (Number(e.currentTarget.name.replace(/\D/g, '')) - 1);
      const prevSibling = document.querySelector(`input[name=${newName}]`) as HTMLInputElement;
      prevSibling?.focus();

      e.preventDefault();
    } else if (e.code === TAB) {
      e.preventDefault();
      if (e.shiftKey) {
        if (item.level > MIN_LEVEL) {
          onUpdateItem({ ...item, level: level - 1 });
        }
      } else {
        if (props.item.level < MAX_LEVEL) {
          onUpdateItem({ ...item, level: level + 1 });
        }
      }
    }
  };

  return (
    <li key={id} className={`${styles.listItem} ${styles[classNameLevel[level]]}`}>
      <div className={styles.itemLine}>
        <input type="checkbox" checked={isChecked} onChange={editItemStatusHandler} name={id} />
        <input
          type="text"
          name={INPUT_NAME + index.toString()}
          value={newValue}
          onChange={updateValueHandler}
          onBlur={updateHandler}
          onKeyDown={keyDownHandler}
          ref={inputRef}
          placeholder="To-do"
          className={isChecked && !isLastItem ? styles.crossed : ''}
        />
        {!isLastItem && (
          <button
            className={`${styles.btnRemove} ${commonStyles.btnRemove} ${commonStyles.btnSquare}`}
            onClick={onRemoveItem.bind(null, id)}
          >
            X
          </button>
        )}
      </div>
    </li>
  );
};

export default ToDoItem;

// frontend/vuejs/src/components/TodoList/TodoItem.vue
<script lang="ts">
import { PropType, ref } from 'vue'
import { MAX_LEVEL, MIN_LEVEL } from './constants'
import { ItemList } from '@/types/common'
import { ARROW_DOWN, ARROW_UP, BACKSPACE, ENTER, TAB } from '@/contants/contants'

export default {
  props: {
    item: { type: Object as PropType<ItemList>, required: true },
    index: Number
  },
  expose: ['setFocus'],
  emits: ['updateItem', 'addNewItem', 'setFocusToElement', 'removeItem'],
  setup(props, { emit }) {
    const input = ref(null)

    const setFocus = () => {
      input.value.focus()
    }

    const onBlurItemHandler = () => {
      emit('updateItem', props.item, props.index)
    }

    const editItemStatusHandler = () => {
      emit('updateItem', { ...props.item, isDone: !props.item.isDone }, props.index)
    }

    const keyDownHandler = (e) => {
      if (e.code === ENTER) {
        if (e.metaKey) {
          editItemStatusHandler()
        } else if (e.currentTarget?.value !== '') {
          emit('addNewItem', {
            value: '',
            index: props.index,
            level: props.item.level,
            id: props.item.id
          })
          emit('setFocusToElement', props.index + 1)
        }
      } else if (e.code === BACKSPACE && props.item.text === '') {
        e.preventDefault()
        emit('setFocusToElement', props.index - 1)
        emit('removeItem', props.item.id)
      } else if (e.code === ARROW_DOWN) {
        emit('setFocusToElement', props.index + 1)
      } else if (e.code === ARROW_UP) {
        emit('setFocusToElement', props.index - 1)
        e.preventDefault()
      } else if (e.code === TAB) {
        e.preventDefault()
        if (e.shiftKey) {
          if (props.item.level > MIN_LEVEL) {
            emit('updateItem', { ...props.item, level: props.item.level - 1 }, props.index)
          }
        } else {
          if (props.item.level < MAX_LEVEL) {
            emit('updateItem', { ...props.item, level: props.item.level + 1 }, props.index)
          }
        }
      }
    }

    const removeItemHandler = () => {
      emit('removeItem', props.item.id)
    }

    return {
      input,
      setFocus,
      keyDownHandler,
      removeItemHandler,
      editItemStatusHandler,
      onBlurItemHandler
    }
  }
}
</script>

<template>
  <div class="itemLine">
    <input type="checkbox" v-model="item.isDone" name="id" />
    <input
      type="text"
      v-model="item.text"
      @keydown="keyDownHandler"
      @blur="onBlurItemHandler"
      placeholder="To-do"
      ref="input"
      :class="{ crossed: item.isDone }"
    />

    <button className="btnRemove btnSquare" @click="removeItemHandler">X</button>
  </div>
</template>

<style scoped>
.itemLine {
  display: flex;
  align-items: center;
}

.listItem .crossed {
  text-decoration: line-through;
}

.listItem button {
  margin: 0 4px;
}

.listItem label {
  display: flex;
  align-items: center;
}

.listItem input[type='checkbox'] {
  height: 20px;
  width: 20px;
}

.listItem input[type='text']:focus-visible {
  outline: none;
}

button.btnRemove:hover {
  background: #f5e0e0;
}

.listItem .btnRemove {
  opacity: 0;
  margin-left: auto;
}

.listItem:hover .btnRemove {
  opacity: 1;
}

.listItem input[type='text'] {
  width: 250px;
}
</style>
